name 'ghoneycutt-timezone'
version '1.0.0'
source 'git://github.com/ghoneycutt/puppet-module-timezone.git'
author 'ghoneycutt'
license 'Apache-2.0'
summary 'Manage system time zone'
description 'Manage system time zone'
project_page 'https://github.com/ghoneycutt/puppet-module-timezone'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
