name 'ngrossmann-timezone'
version '1.0.0'
source 'git://github.com/time/puppet-module-timezone.git'
author 'ngrossmann'
license 'Apache License, Version 2.0'
summary 'Manage system time zone'
description 'Manage system time zone'
project_page 'https://github.com/time/puppet-module-zone'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
