name 'timezone'
version '0.1.0'
source 'git://github.com/time/puppet-module-zone.git'
author 'time'
license 'Apache License, Version 2.0'
summary 'put a summary here'
description 'Set system time-zone'
project_page 'https://github.com/time/puppet-module-zone'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
